{
 "title": "Ping",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ICMP Duration",
   "type": "graph",
   "description": "5 min average RTT duration",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(probe_icmp_duration_seconds{phase=\"rtt\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Host Status",
   "type": "graph",
   "description": "1- host is up, 0 - host unreachable",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe Status",
   "type": "graph",
   "description": "1 - blackbox probe is up, 0 - probe is down",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=\"blackbox\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}